server.port=${PORT:8080}
logging.level.org.atmosphere=warn

vaadin.launch-browser=true

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DBNAME}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.genetico
vaadin.copilot.enabled=false
