server.port=${PORT:8080}
logging.level.org.atmosphere=warn

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DBNAME}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.genetico
vaadin.copilot.enabled=false

locationiq.api.key=${IQ_API}
