ALTER TABLE enderecos
ADD COLUMN numero INT NOT NULL;

ALTER TABLE enderecos
ADD COLUMN bairro VARCHAR(255) NOT NULL;

ALTER TABLE enderecos
ADD COLUMN complemento VARCHAR(255);

ALTER TABLE enderecos
ADD COLUMN cep VARCHAR(20) NOT NULL;